In [1]:
# NumPY - Arrays

In [2]:
import numpy as np

In [3]:
matr = [1,2,3,4,5,6,7,8,9]

In [4]:
matr = np.array(matr)

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.linspace(0,4,6)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

In [8]:
np.random.randn(4,2)

array([[-1.55476493,  0.31979585],
       [ 0.01588376,  0.49391543],
       [ 0.31599842,  0.4201711 ],
       [-0.53881122,  1.46311146]])

In [9]:
myarr = np.random.randint(1,50,15) #1-dim 

In [10]:
myarr.max();myarr.min() #value

1

In [11]:
myarr.argmax();myarr.argmin() #index 

1

In [12]:
rearr = myarr.reshape(5,3) #reshape the 1-dim to any

In [13]:
rearr.shape

(5, 3)

In [14]:
rearr.dtype

dtype('int32')

In [15]:
matr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [16]:
slice = matr[0:4] 

In [17]:
slice[:] = 2

In [18]:
slice

array([2, 2, 2, 2])

In [19]:
matr #لاحظ سمعت ف arr الاصليه    so we use arr.copy() 

array([2, 2, 2, 2, 5, 6, 7, 8, 9])

In [20]:
arr2d = np.array([[12,33,67],[44,2,78],[0,3,22]])

In [21]:
arr2d[1][2] # arr2d[1,2]

78

In [22]:
arr2d[1:2 , 0:]

array([[44,  2, 78]])

In [23]:
arr2d > 5 ; arr2d[arr2d > 5]   # compare and return False/True ; return elements

array([12, 33, 67, 44, 78, 22])

In [24]:
 arr2d + arr2d

array([[ 24,  66, 134],
       [ 88,   4, 156],
       [  0,   6,  44]])